myFirstExtension/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<pk>[0-9]+)/posts_display/$', views.IndexView.as_view(), name='posts_display'),
    url(r'^1/clean_data_bases/$', views.clean_data_bases, name='clean_data_bases'),
    url(r'^1/clean_one_user_data/$', views.clean_one_user_data, name='clean_one_user_data'),
    url(r'^([0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<user_id>[0-9]+)/saving/$', views.saving, name='saving'),
    url(r'^([0-9]+)/start_scan/$', views.start_scan, name='start_scan'),
    url(r'^([0-9]+)/log_out/$', views.log_out, name='log_out'),
    url(r'^([0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    

#     url(r'^homepage/$', views.DetailView.as_view(), name='asdfsa'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.template.defaultfilters import default
from django.contrib.auth.models import User

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __unicode__(self):            
		return self.question_text
		
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)		
		
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
	
    def __unicode__(self):           
		return self.choice_text
 	
# 	def __unicode__(self):		   
# 		return self.choice_text
 	
class Groups(models.Model):
	group_name = models.CharField(max_length=200)
	group_link = models.CharField(max_length=200, default='default')
	user_own = models.ForeignKey(User , related_name='Groups_user_own')
	is_important = models.IntegerField(default=0)
	keyword = models.CharField(max_length=200)
# 	
# 	def __unicode__(self):		   
# 		return self.choice_text

class Posts(models.Model):
	user_who_post = models.ForeignKey(User)
	group_that_was_post = models.ForeignKey(Groups)
	keyword = models.CharField(max_length=200)
	post_text = models.TextField()
	link =  models.CharField(max_length=500)
	pub_date = models.IntegerField()
	
class Scans(models.Model):
	time_of_the_scan = models.IntegerField()

polls/views.py
import bz2
import calendar
from datetime import date
from lib2to3.fixer_util import is_import
import threading
import time

from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect , HttpResponse
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.views import generic
from django.views.generic import DetailView

from myFirstExtension import phone_from_facebook
from polls.models import Posts, Scans

from .models import Choice, Question , Groups


class IndexView(generic.DetailView):
    def get_object(self):
        print 168
        try:
            user_by_the_url = User.objects.get(pk=self.kwargs['pk'])
        except User.DoesNotExist: 
            print 190  
            return None
        print 8798
        return user_by_the_url
        
        
        
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IndexView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['last_scan'] = Scans.objects.order_by('-id')[0]
        return context        
    
    
    def get_template_names(self):
        print 123
        try:
            user_by_the_url = User.objects.get(pk=self.kwargs['pk'])
        except User.DoesNotExist:  
            return 'polls/detail.html'
        user_by_session =  self.request.user
        if user_by_the_url == user_by_session:
            return 'polls/index.html'
        else:    
            return 'polls/detail.html'
        
    
class DetailView(generic.DetailView):
    def get_object(self):
        IndexView()
        if self.request.user.is_authenticated():
            return self.request.user
        else:    
            return None
 
    def get_template_names(self):
        if self.request.user.is_authenticated():
            return 'polls/index.html'
        else:    
            return 'polls/detail.html'
        
        
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(DetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        if self.request.user.is_authenticated():
            context['last_scan'] = Scans.objects.order_by('-id')[0]
        return context    
 
class ResultsView(generic.DetailView):
    model = User
    template_name = 'polls/results.html'
 
def vote(request,asdsad):
    user_email =  request.POST['email']
    user_password =  request.POST['password']
    
    user = authenticate(username=user_email, password=user_password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('polls:posts_display', args=(user.id,)))  
    else:
        if new_user_register(user_email , user_password):
            new_user = authenticate(username=user_email, password=user_password)
            login(request, new_user)
            return HttpResponseRedirect(reverse('polls:results', args=(new_user.id,)))
        else:
            return HttpResponse("there is no group to show - maybe the password or name was not correct , and maybe you dont have any groups") 

     
def saving(request, user_id):
    all_checked_groups = request.POST.getlist("group_to_mark")
    keyword = request.POST['keyword'] 
    for a in all_checked_groups:
        p = get_object_or_404(Groups, pk=a)
        p.is_important=1
        p.keyword = keyword
        p.save()
    first_scan_for_user(user_id)
    user = User.objects.get(id = user_id)
    return HttpResponseRedirect(reverse('polls:posts_display', args=(user.id,)))  

def scan_thread():
    while(True):
        print "start check"
        all_users =  User.objects.all()
        for user in all_users:
                look_for_new_posts(user.id)
        print 'Worker'
        time.sleep(60)

def start_scan(request, question_id):
    epoch_time = int(time.time())
    new_scan = Scans(time_of_the_scan = epoch_time)
    new_scan.save()
    Posts.objects.all().delete()
    t = threading.Thread(target=scan_thread)
    t.start()
    return HttpResponse("Here's the text of the Web page.") 

def first_scan_for_user(user_id):
    epoch_time = int(time.time())
    new_scan = Scans(time_of_the_scan = epoch_time)
    new_scan.save()
    look_for_new_posts(user_id)

  
def look_for_new_posts(user_id):
    user = User.objects.get(id = user_id)
#     user_details = {"user_mail":user.email , "user_password":user.password}
    relevant_groups = Groups.objects.filter(user_own =user , is_important = "1")
    FB_phone =  phone_from_facebook.facebook_phone(user.username ,user.first_name )
    FB_phone.get_the_relevant_posts(relevant_groups)
    
def clean_data_bases(request):
    User.objects.all().delete()
    Groups.objects.all().delete()
    Posts.objects.all().delete()
    return HttpResponse("we cleaned all") 

def clean_one_user_data(request):
    print "lalala"
    user_name =  request.POST['username']
    print user_name
    user = User.objects.get(username = user_name)
    Posts.objects.filter(user_who_post_id = user.id).delete()
    Groups.objects.filter(user_own_id = user.id).delete()
    user.delete()
    return HttpResponse("we cleaned one user") 

def new_user_register(user_email , user_password):
        FB_phone =  phone_from_facebook.facebook_phone(user_email , user_password)
        list_of_all_groups = FB_phone.get_all_group_of_user()
        if len(list_of_all_groups)>0:
            user = User.objects.create_user(password = user_password , username = user_email ,first_name = user_password)           
            user.save()
            print "check groups link"
            for group in list_of_all_groups: 
                print group["link"]
                new_group = Groups(group_name = group["name"] ,group_link = group["link"], user_own = user)
                new_group.save()  
            return user             
        else:
            return False
    
def log_out(request,blaasd):
    user = request.user
    logout(request)
    return HttpResponseRedirect(reverse('polls:detail', args=(user.id,)))  

polls/templates/polls/detail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/polls/1/vote/" method="post">
{% csrf_token %}

enter email:  
<input id="email" type="text" name="email" value="asaelcorem@gmail.com">
<br><br>
enter password:  
<input id="password" type="password" name="password" value="asaf0587">
<br><br>
<input type="submit" value="add new user" />
</form>
<br><br>

<a target="_blank" 
	id="scan_posts"
    class="btn btn-info pull-right" 
    href="/polls/1/start_scan/">
    scan for post
</a>
<br><br>
<a target="_blank" 
	id="deleteAll"
    class="btn btn-info pull-right" 
    href="/polls/1/clean_data_bases/">
</a>

<br><br>
<input name="myBtn" type="button" onClick="deleteImage('images/pic.jpg')" value="Delete all data base">

<script type="text/javascript">
function deleteImage(x){
    var conf = confirm("Are you sure you want to delete this image?");
    if(conf == true){
		document.getElementById("deleteAll").click();    }
}
</script>

<br><br>

<form action="/polls/1/clean_one_user_data/" method="post">
{% csrf_token %}

enter username to delete:  
<input id="username" type="text" name="username" value="asaelcorem@gmail.com">
<br><br>
<input type="submit" value="delete user" />
</form>
<br><br>

polls/templates/polls/index.html
{{ last_scan.time_of_the_scan }}

{% if  user  %}
    <ul>
    {% for group in  user.Groups_user_own.all %}
			{% if group.is_important == 1 %}
			<h1><p style="text-align:right">{{ group.group_name }}</p></h1>
			<p style="text-align:right">------------------------------------</p>
	    	{% for post in group.posts_set.all|dictsort:"pub_date" %}
	    		<br>
	    		{% if  last_scan.time_of_the_scan < post.pub_date  %}
	        	<h1><li><p style="text-align:right"><a href="https://www.facebook.com/groups/{{ group.group_link }}permalink/{{post.link}}/">{{ post.post_text }}</a></li></h1></p>
	        	<br>
	    		{% else %}
	    		<br>
	    		<li><p style="text-align:right"><a href="https://www.facebook.com/groups/{{ group.group_link }}permalink/{{post.link}}/">{{ post.post_text }}</a></li></p>
	    		{% endif %}
			{% endfor %}
                {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<br>


<a target="_blank" 
	id="log_out"
    class="btn btn-info pull-right" 
    href="/polls/1/log_out/">
    log out
</a>

polls/templates/polls/results.html
aaaaaaaaaaa
<h1>{{ user.id }}</h1>

<form action="{% url 'polls:saving' user.id %}" method="post">
{% csrf_token %}

{% for group in user.Groups_user_own.all %}
    <input type="checkbox" name="group_to_mark" id="group{{ forloop.counter }}" value="{{ group.id }}" />
    <label for="group{{ forloop.counter }}">{{ group.group_name }}</label><br />
{% endfor %}

<br><br>
enter fucking keyword:  
<input id="keyword" type="text" name="keyword">

<input type="submit" value="saving" />

</form>